### ISSUE TITLE
Unable to run titiler.application.main:app  ERROR: AttributeError: 'CRS' object has no attribute 'axis_info'

### ISSUE THREAD

**Issue by dBitech** [developmentseed/titiler#418]
Error:
```[user@raster ~]$ uvicorn titiler.application.main:app --reload               INFO:     Will watch for changes in these directories: ['/usr/home/user']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [10151] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/config.py", line 456, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/.local/lib/python3.8/site-packages/titiler/application/main.py", line 7, in <module>
    from titiler.application.custom import templates
  File "/home/user/.local/lib/python3.8/site-packages/titiler/application/custom.py", line 47, in <module>
    EPSG3413 = morecantile.TileMatrixSet.custom(
  File "/home/user/.local/lib/python3.8/site-packages/morecantile/models.py", line 271, in custom
    is_inverted = crs_axis_inverted(crs)
  File "/home/user/.local/lib/python3.8/site-packages/morecantile/models.py", line 76, in crs_axis_inverted
    return crs.axis_info[0].abbrev.upper() in ["Y", "LAT", "N"]
AttributeError: 'CRS' object has no attribute 'axis_info'
INFO:     Stopping reloader process [10151]
[user@raster ~]$
```
Environment, Python version & Installed packages:
```
[user@raster ~]$ uname -a
FreeBSD raster 13.0-RELEASE-p4 FreeBSD 13.0-RELEASE-p4 #0: Tue Aug 24 07:33:27 UTC 2021     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
[user@raster ~]$ python -V
Python 3.8.12
[user@raster ~]$ pip list
Package             Version
------------------- ---------
affine              2.3.0
anyio               3.4.0
asgiref             3.4.1
attrs               21.2.0
boto3               1.20.26
botocore            1.23.26
Brotli              1.0.9
brotli-asgi         1.1.0
cachetools          5.0.0
certifi             2021.5.30
charset-normalizer  2.0.9
click               7.1.2
click-plugins       1.1.1
cligj               0.7.2
cogeo-mosaic        4.0.0
fastapi             0.67.0
geojson-pydantic    0.3.1
h11                 0.12.0
httpcore            0.14.3
httpx               0.21.1
idna                3.3
importlib-resources 5.4.0
Jinja2              2.11.3
jmespath            0.10.0
MarkupSafe          2.0.1
mercantile          1.2.1
morecantile         3.0.3
numexpr             2.8.1
numpy               1.16.6
packaging           21.3
pip                 21.3.1
pipenv              2021.5.29
pydantic            1.8.2
pygeos              0.12.0
pyparsing           2.4.7
pyproj              3.2.1
pystac              1.2.0
python-dateutil     2.8.2
python-dotenv       0.19.2
rasterio            1.2.8
rfc3986             1.5.0
rio-cogeo           3.0.2
rio-color           1.0.4
rio-mucho           1.0.0
rio-tiler           3.0.1
s3transfer          0.5.0
setuptools          57.0.0
simplejson          3.17.6
six                 1.16.0
sniffio             1.2.0
snuggs              1.4.7
starlette           0.14.2
supermercado        0.2.0
titiler.application 0.3.9
titiler.core        0.4.0
titiler.mosaic      0.4.0
typing_extensions   4.0.1
urllib3             1.26.7
uvicorn             0.16.0
virtualenv          16.7.5
virtualenv-clone    0.5.4
zipp                3.6.0
```

**Comment by vincentsarago** [comment]
@dBitech not sure what's going on with your install. 

could you try to run 👇  and print the result here.
```python

from pyproj import CRS

crs_3413 = CRS.from_epsg(3413)
print(crs_3413)
print(crs_3413.axis_info)
```

It's likely that you have a PyProj install issue

**Comment by dBitech** [comment]
```[user@raster ~]$ python pyprog-test.py
epsg:3413
[Axis(name=Easting, abbrev=X, direction=south, unit_auth_code=EPSG, unit_code=9001, unit_name=metre), Axis(name=Northing, abbrev=Y, direction=south, unit_auth_code=EPSG, unit_code=9001, unit_name=metre)]
[user@raster ~]$```

If it helps I should also say this is on a FreeBSD 13 system.

**Comment by vincentsarago** [comment]
@dBitech I don't understand, if the previous code worked, I don't see why titiler won't 🤷‍♂️

**Comment by dBitech** [comment]
I think what's going on in the crs is being passed in uninitialized:
 ```[user@raster ~]$ diff ~/.local/lib/python3.8/site-packages/morecantile/models.py-bak ~/.local/lib/python3.8/site-packages/morecantile/models.py
--- ~/.local/lib/python3.8/site-packages/morecantile/models.py-bak   2022-01-03 09:40:49.450760000 -0800
+++ ~/.local/lib/python3.8/site-packages/morecantile/models.py       2022-01-03 09:40:37.344951000 -0800
@@ -73,6 +73,8 @@

 def crs_axis_inverted(crs: CRS) -> bool:
     """Check if CRS has inverted AXIS (lat,lon) instead of (lon,lat)."""
+    from pprint import pprint
+    pprint(vars(crs))
     return crs.axis_info[0].abbrev.upper() in ["Y", "LAT", "N"]
```
results in:
```
[user@raster ~]$ uvicorn titiler.application.main:app --host 0.0.0.0 --reload
INFO:     Will watch for changes in these directories: ['/usr/home/user']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [3871] using statreload
{'_crs': <rasterio._crs._CRS object at 0x82d5fbac0>,
 '_data': None,
 '_wkt': None}
Process SpawnProcess-1:
Traceback (most recent call last):
..........
```

**Comment by vincentsarago** [comment]
wait `crs` shouldn't be of type `rasterio._crs._CRS` here, let me have a look

**Comment by vincentsarago** [comment]
yep 
```
titiler.application 0.3.9
```

please update titiler.application to `0.4.0`

**Comment by vincentsarago** [comment]
@dBitech I'm sorry about the time you lost on this. the previous version (~0.3) of `titiler.application` didn't had titiler.core or titiler.mosaic version pinned, which in your case resulted in some breaking code. This is now fixed.
