### ISSUE TITLE
0.6.0a1 breaks namespace packages

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#471]
```
# pip install titiler==0.5.1 --no-cache
$ ls -la /Users/vincentsarago/Dev/venv/dev/lib/python3.8/site-packages | grep "titiler"
drwxr-xr-x    5 vincentsarago  staff       160 May 11 16:33 titiler
drwxr-xr-x    9 vincentsarago  staff       288 May 11 16:33 titiler-0.5.1.dist-info
drwxr-xr-x    7 vincentsarago  staff       224 May 11 16:33 titiler.application-0.5.1.dist-info
drwxr-xr-x    7 vincentsarago  staff       224 May 11 16:33 titiler.core-0.5.1.dist-info
drwxr-xr-x    7 vincentsarago  staff       224 May 11 16:33 titiler.mosaic-0.5.1.dist-info

# pip install titiler==0.6.0a1 --no-cache
$ ls -la /Users/vincentsarago/Dev/venv/dev/lib/python3.8/site-packages | grep "titiler"
drwxr-xr-x    5 vincentsarago  staff       160 May 11 16:31 titiler
drwxr-xr-x    9 vincentsarago  staff       288 May 11 16:31 titiler-0.6.0a1.dist-info
drwxr-xr-x    6 vincentsarago  staff       192 May 11 16:31 titiler_application-0.6.0a1.dist-info
drwxr-xr-x    6 vincentsarago  staff       192 May 11 16:31 titiler_core-0.6.0a1.dist-info
drwxr-xr-x    6 vincentsarago  staff       192 May 11 16:31 titiler_mosaic-0.6.0a1.dist-info
```

```
$ python -c 'from importlib.metadata import version; print(version("titiler"))'       
0.6.0a1

$ python -c 'from importlib.metadata import version; print(version("titiler.core"))'  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 531, in version
    return distribution(distribution_name).version
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: titiler.core
```

**Comment by vincentsarago** [comment]
links:
- https://github.com/pypa/flit/issues/442
- https://github.com/pypa/warehouse/pull/10072
- https://github.com/pypa/warehouse/issues/10030

I don't think there is another choice than to move back to setup.py here 😭
