### ISSUE TITLE
Issue with pydantic-settings, Extra inputs are not permitted

### ISSUE THREAD

**Issue by imanshafiei540** [developmentseed/titiler#799]
#### Problem description

I encountered an error related to the `rio_tiler_max_threads` environment variable when using TiTiler with the following environment configuration:

`.env` file:
```
RIO_TILER_MAX_THREADS=50
```

`pyproject.toml` file:
```toml
dependencies = [
    ...
    "pydantic-settings~=2.0",
]
```

`pip freeze` output:
```
pydantic-settings==2.2.1
```

The error occurred with the current implementation:
```python
model_config = SettingsConfigDict(env_prefix="TITILER_API_", env_file=".env")
```

The error message is:
```
rio_tiler_max_threads
  Extra inputs are not permitted [type=extra_forbidden, input_value='50', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/extra_forbidden
```

#### Expected Output

No errors when loading the environment variables.

#### Proposed Fix

I fixed the issue by allowing extra settings in the `SettingsConfigDict`:
```python
model_config = SettingsConfigDict(env_prefix="TITILER_API_", env_file=".env", extra="allow")
```

#### Environment Information

- Python Version: 3.11
- TiTiler Version: 0.17.1

**Comment by vincentsarago** [comment]
@imanshafiei540 this is really weird because `RIO_TILER_MAX_THREADS` doesn't conflict with `TITILER_API_` prefix 🤷

**Comment by imanshafiei540** [comment]
Okay, I tried to dig more into the issue and ended up here in this line from `Pydantic==2.6.4`:

```
self.__pydantic_validator__.validate_python(data, self_instance=self)
```

Somehow, the `api_settings = ApiSettings()` coming from `src/titiler/application/titiler/application/main.py` cannot be validated by `__pydantic_validator__` and I'm not sure what's the reason.

Could be some issues between `Pydantic` and `Pydantic-Settings.`

I hope someone else can also verify the issue; I'm constantly thinking maybe I'm doing something wrong on my end.

Anyway, thank you for the quick response, and I'll try to figure out what's wrong; it's probably time to raise an issue on the Pydantic-Setiings repo.

**Comment by vincentsarago** [comment]
can you share the full `log`? and/or share a reproducible example 🙏

**Comment by imanshafiei540** [comment]
Sure, I'll prepare something ASAP, just as a note, everything is working with `pydantic-settings==2.1.0`
`2.2.0` or above will break the TiTiler.

**Comment by vincentsarago** [comment]
ok I've been able to reproduce this 

```
uvicorn titiler.application.main:app --port 8000 --reload
INFO:     Will watch for changes in these directories: ['/Users/vincentsarago/Dev/DevSeed/titiler']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [79319] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vincentsarago/Dev/venv/py39/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/vincentsarago/Dev/venv/py39/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/vincentsarago/Dev/venv/py39/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/Users/vincentsarago/Dev/venv/py39/lib/python3.9/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/vincentsarago/Dev/venv/py39/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/vincentsarago/Dev/DevSeed/titiler/src/titiler/application/titiler/application/main.py", line 51, in <module>
    api_settings = ApiSettings()
  File "/Users/vincentsarago/Dev/venv/py39/lib/python3.9/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/Users/vincentsarago/Dev/venv/py39/lib/python3.9/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ApiSettings
rio_tiler_max_threads
  Extra inputs are not permitted [type=extra_forbidden, input_value='50', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
```

This is really weird and I wonder if this is a pydantic-setting bug instead of a titiler one. 

pydantic ticket: https://github.com/pydantic/pydantic-settings/issues/245

I would be happy to review any PR to add `extra='ignore'` 👍

**Comment by imanshafiei540** [comment]
Thanks for confirming the issue. I'll try to create a PR as soon as possible.
